name: color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSV, LAB, RGB,
  and XYZ color spaces with methods to convert colors between each space.
version: 0.3.0
homepage: https://github.com/james-alex/color_models

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2
