name: color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSV, LAB, RGB,
  and XYZ color spaces with methods to convert colors between each space.
version: 0.1.0+2
author: James Alexander <j.alex@email.com>
homepage: https://github.com/james-alex/color_models

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5
